FROM tensorflow/tensorflow:2.8.4-gpu as base

# install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    swig \
    wget \
    virtualenv \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libc6-dev \
    libosmesa6-dev \
    patchelf \
    software-properties-common \
    gfortran \
    && apt-get install --no-install-recommends -y file g++ gcc make gdb strace ca-certificates \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get --no-install-recommends install -y python3.8-dev python3.8 python3-pip \
    && apt-get clean
#    && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y libopenexr-dev
RUN apt-get install -y openexr
RUN apt-get install -y zlib1g-dev

# INSTALL MPI
RUN wget -q http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz
RUN tar xf mpich-3.1.4.tar.gz
WORKDIR mpich-3.1.4
RUN ./configure --disable-fortran --enable-fast=all,O3 --prefix=/usr
RUN make -j$(nproc)
RUN make install
RUN ldconfig
WORKDIR /

# ENVIRONMENT VARIABLES
ENV LD_LIBRARY_PATH="/usr/lib/nvidia:$LD_LIBRARY_PATH"
ENV LD_LIBRARY_PATH="/usr/local/nvidia/lib64:$LD_LIBRARY_PATH"
ENV LD_LIBRARY_PATH="/usr/local/cuda-11.2/lib64:$LD_LIBRARY_PATH"
ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/usr/local/cuda-11.1/lib64"

# matplotlib
ENV MPLCONFIGDIR=/var/cache/matplotlib

# SETUP ENV
ENV VIRTUAL_ENV=/venv
RUN virtualenv --python=python3.8 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install pip --upgrade

RUN pip install --upgrade setuptools

# INSTALL TOOL
RUN mkdir /ang_tmp
COPY . /ang_tmp

RUN pip install /ang_tmp --default-timeout=100 \
    && rm -rf /ang_tmp

RUN pip install tensorflow_datasets
RUN pip install mujoco_utils
RUN pip install protobuf==3.20.0

WORKDIR /

COPY angorapy/train.py train.py
COPY angorapy/pretrain.py pretrain.py
COPY angorapy/analysis/predictability.py predictability.py

# FINAL
CMD [ "/bin/bash" ]
