FROM tensorflow/tensorflow:2.5.2-gpu as base

# install packages
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    curl \
    git \
    swig \
    wget \
    virtualenv \
    libgl1-mesa-dev \
    libgl1-mesa-glx \
    libglew-dev \
    libc6-dev \
    libosmesa6-dev \
    patchelf \
    software-properties-common \
    gfortran \
    && apt-get install --no-install-recommends -y file g++ gcc make gdb strace ca-certificates \
    && add-apt-repository -y ppa:deadsnakes/ppa \
    && apt-get update \
    && apt-get --no-install-recommends install -y python3.9-dev python3.9 python3-pip \
    && apt-get clean
#    && rm -rf /var/lib/apt/lists/*

RUN apt-get install -y libopenexr-dev
RUN apt-get install -y openexr
RUN apt-get install -y zlib1g-dev

# INSTALL MPI
RUN wget -q http://www.mpich.org/static/downloads/3.1.4/mpich-3.1.4.tar.gz
RUN tar xf mpich-3.1.4.tar.gz
WORKDIR mpich-3.1.4
RUN ./configure --disable-fortran --enable-fast=all,O3 --prefix=/usr
RUN make -j$(nproc)
RUN make install
RUN ldconfig
WORKDIR /

# ENVIRONMENT VARIABLES

# SETUP ENV
ENV VIRTUAL_ENV=/venv
RUN virtualenv --python=python3.9 $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install pip --upgrade
RUN pip install --upgrade setuptools

# INSTALL TOOL
RUN mkdir /ang_tmp
COPY . /ang_tmp

RUN pip install /ang_tmp --default-timeout=100 \
    && rm -rf /ang_tmp

RUN pip install numpy==1.21.0
RUN pip install gymnasium[box2d,mujoco]==0.28.1
RUN pip install dm_control==1.0.12 tensorflow_datasets mujoco_utils tensorflow_probability==0.12.2
RUN pip install protobuf==3.20.0

# matplotlib
ENV MPLCONFIGDIR=/var/cache/matplotlib

WORKDIR /

COPY angorapy/train.py train.py
COPY angorapy/pretrain.py pretrain.py
COPY angorapy/analysis/predictability.py predictability.py

# FINAL
CMD [ "/bin/bash" ]
